export const FENTCHBANNER = 'FENTCHBANNER'

export const FENTCHHOTCOMMEND = 'FENTCHHOTCOMMEND'

export const FENTCHNEWALBUM= 'FENTCHNEWALBUM'

export const FENTCHUPRANK = 'FENTCHUPRANK'

export const FENTCHNEWRANK = 'FENTCHNEWRANK'

export const FENTCHORG = 'FENTCHORG'